run:
    concurrency: 8
    timeout: 2m
    issues-exit-code: 1
    tests: false

linters-settings:
    gocognit:
        min-complexity: 15
    gocyclo:
        min-complexity: 15
    gofmt:
        simplify: true
    gosimple:
        go: "1.17"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    govet:
        check-shadowing: true
        enable-all: true
    nestif:
        min-complexity: 5
    staticcheck:
        go: "1.17"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    stylecheck:
        go: "1.17"
        checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]
    thelper:
        test:
            first: true
            name: true
            begin: true
        benchmark:
            first: true
            name: true
            begin: true
        tb:
           first: true
           name: true
           begin: true
    unused:
        go: "1.17"

linters:
    disable-all: false
    disable:
        - gochecknoinits
        - interfacer
        - golint
        - scopelint
        - maligned
        - gofumpt
        - goimports
        - lll
        - wsl
        - exhaustivestruct
        - gochecknoglobals
        - nlreturn
        - varnamelen
        - wrapcheck
        - goerr113
        - forbidigo
        - ireturn
        - noctx
        - tagliatelle
        - gomnd
    enable-all: true
    fast: false

issues:
    max-issues-per-linter: 0
    max-same-issues: 0
    fix: true
